# Generated by Django 4.0.1 on 2022-05-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPDapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedmaster',
            name='ward_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardcate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedmaster',
            name='ward_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardtype'),
            preserve_default=False,
        ),
    ]
