# Generated by Django 4.0.1 on 2022-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPDapp', '0002_bedmaster_ward_category_bedmaster_ward_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedMasterMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing_name', models.CharField(max_length=40)),
                ('floor_name', models.CharField(max_length=40)),
                ('room_number', models.CharField(max_length=40)),
                ('bed_no', models.CharField(max_length=30)),
                ('ward_type', models.CharField(max_length=40)),
                ('ward_category', models.CharField(max_length=40)),
                ('bed_location', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bedmaster',
            name='bed_location',
            field=models.CharField(choices=[('WINDOWS SIDE', 'WINDOWS SIDE'), ('CENTER', 'CENTER'), ('LEFT SIDE', 'LEFT SIDE'), ('RIGHT SIDE', 'RIGHT SIDE')], max_length=100),
        ),
    ]
