# Generated by Django 4.0.1 on 2022-09-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPDapp', '0003_bedmastermain_alter_bedmaster_bed_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioninfos',
            name='bed_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.bedmaster'),
        ),
    ]
