# Generated by Django 4.0.1 on 2022-11-30 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0056_consultation_main_consultationtemp_and_more'),
        ('IPDapp', '0005_alter_admissioninfos_bed_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipd_Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('doctor_transfer_id', models.CharField(max_length=50)),
                ('transfer_datatime', models.DateField(default=datetime.datetime.now)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_doctor', to='IPDapp.ipd_dept')),
                ('from_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dept', to='testapp.doctortable')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_doctor', to='IPDapp.ipd_dept')),
                ('to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dept', to='testapp.doctortable')),
            ],
        ),
        migrations.CreateModel(
            name='Bed_Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('bed_transfer_id', models.CharField(max_length=50)),
                ('transfer_datatime', models.DateField(default=datetime.datetime.now)),
                ('from_bed_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_bed_no', to='IPDapp.bedmastermain')),
                ('from_ward_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ward_type', to='IPDapp.admissionwardcate')),
                ('from_ward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ward_type', to='IPDapp.admissionwardtype')),
                ('to_bed_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_bed_no', to='IPDapp.bedmastermain')),
                ('to_ward_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ward_type', to='IPDapp.admissionwardcate')),
                ('to_ward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ward_type', to='IPDapp.admissionwardtype')),
            ],
        ),
    ]
