# Generated by Django 4.0.1 on 2022-12-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0106_alter_centralisedadminview_date_and_more'),
        ('IPDapp', '0007_admissioninfos_admission_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomDefination',
            new_name='Room_Defination',
        ),
        migrations.AddField(
            model_name='admissioninfos',
            name='status',
            field=models.CharField(blank=True, default='admitted', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionwardcate',
            name='floor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.floormaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionwardcate',
            name='room_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.roommaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionwardcate',
            name='ward_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionwardtype',
            name='floor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.floormaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionwardtype',
            name='room_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.roommaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bed_transfer',
            name='admission_ID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedmastermain',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Occupied', 'Occupied'), ('Un-occupied', 'Un-occupied')], default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor_transfer',
            name='admission_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissioninfos',
            name='bed_no',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.bedmastermain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissioninfos',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='IPDapp.ipd_dept'),
        ),
        migrations.AlterField(
            model_name='admissioninfos',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_doctor', to='testapp.doctortable'),
        ),
        migrations.AlterField(
            model_name='admissioninfos',
            name='ref_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.hospitalmaster'),
        ),
        migrations.AlterField(
            model_name='admissioninfos',
            name='req_ward_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardcate'),
        ),
        migrations.AlterField(
            model_name='admissioninfos',
            name='req_ward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.admissionwardtype'),
        ),
        migrations.AlterField(
            model_name='admissioninfos',
            name='secondary_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secoundry_doctor', to='testapp.doctortable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed_transfer',
            name='bed_transfer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bed_transfer',
            name='transfer_datatime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room_defination',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='testapp.roomnumber'),
        ),
    ]
