# Generated by Django 4.0.1 on 2022-05-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBelongsToMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_Id', models.CharField(max_length=100)),
                ('Item_name', models.CharField(choices=[('counter1', 'Counter1'), ('counter2', 'Counter2')], max_length=100)),
                ('store_name', models.CharField(choices=[('store1', 'Store1'), ('store2', 'Store2')], max_length=100)),
                ('location', models.CharField(choices=[('dept1', 'Dept1'), ('dept2', 'Dept2')], max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('inactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemManufact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactures', models.CharField(choices=[('manufacturers1', 'manufacturers1'), ('manufacturers2', 'manufacturers2')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers', models.CharField(choices=[('suppliers1', 'Suppliers1'), ('suppliers2', 'Suppliers2')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemUnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManufactureTempTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackagigMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_packing', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_Id', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('parent_store', models.CharField(choices=[('store1', 'store1'), ('store2', 'store2')], max_length=100)),
                ('wing', models.CharField(choices=[('store1', 'Store1'), ('store2', 'Store2')], max_length=100)),
                ('floor', models.CharField(choices=[('store1', 'Store1'), ('store2', 'Store2')], max_length=100)),
                ('location_name', models.CharField(choices=[('store1', 'Store1'), ('store2', 'Store2')], max_length=100)),
                ('store_type', models.CharField(choices=[('store1', 'Store1'), ('store2', 'Store2')], max_length=100)),
                ('main_store', models.BooleanField()),
                ('inactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreNursingCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storelinkId', models.CharField(max_length=100)),
                ('store', models.CharField(choices=[('store1', 'Store1'), ('store2', 'Store2')], max_length=100)),
                ('nursingcounter', models.CharField(choices=[('counter1', 'Counter1'), ('counter2', 'Counter2')], max_length=100)),
                ('department', models.CharField(choices=[('dept1', 'Dept1'), ('dept2', 'Dept2')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuppliersTempTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VendorMasterr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_short_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('city1', 'Chennai'), ('city2', 'Salem')], max_length=100)),
                ('district', models.CharField(choices=[('district1', 'Chennai'), ('district2', 'Salem')], max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=100)),
                ('phone2', models.CharField(max_length=100)),
                ('fax_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=100)),
                ('afc_code', models.CharField(max_length=100)),
                ('type_char', models.CharField(max_length=100)),
                ('inactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_reuse', models.CharField(max_length=100)),
                ('serial_batch_control', models.CharField(max_length=100)),
                ('reusable_rate', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('shortcode', models.CharField(max_length=100)),
                ('contain', models.CharField(max_length=100)),
                ('conversion_factor', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(max_length=100)),
                ('hospital_item_code', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('Gst', models.CharField(choices=[('gst1', 'Gst1'), ('gst2', 'Gst2')], max_length=100)),
                ('min_quantity', models.CharField(max_length=100)),
                ('max_quantity', models.CharField(max_length=100)),
                ('re_order_level', models.CharField(max_length=100)),
                ('suppliers', models.CharField(choices=[('suppliers1', 'Suppliers1'), ('suppliers2', 'Suppliers2')], max_length=100)),
                ('generic', models.CharField(choices=[('gen1', 'gen1'), ('gen2', 'gen2')], max_length=100)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itembelongstomaster')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemcategorymaster')),
                ('manufacturers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemmanufacturer')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.packagigmaster')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemunitmaster')),
            ],
        ),
    ]
