# Generated by Django 4.0.1 on 2022-10-12 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_corporatemaster_cash_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 12)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 12)),
        ),
        migrations.CreateModel(
            name='ServiceChargeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('service_charge', models.CharField(max_length=50)),
                ('applicable_date', models.DateField()),
                ('inactive', models.BooleanField()),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster')),
                ('ward_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardcategory')),
                ('ward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardtype')),
            ],
        ),
    ]
