# Generated by Django 4.0.1 on 2022-10-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargemaster',
            name='inactive',
            field=models.BooleanField(default=True),
        ),
    ]
