# Generated by Django 4.0.1 on 2022-10-18 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_alter_servicechargemaster_inactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50)),
                ('bill_date_time', models.DateTimeField(auto_now_add=True)),
                ('uhid', models.CharField(max_length=50)),
                ('visit_no', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('discount', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('net_ammount', models.FloatField()),
                ('outstanding_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('receive_amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='bill_date_time',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='net_ammount',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='outstanding_amount',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='receive_amount',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='uhid',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='visit_no',
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 18)),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='extra_fields',
            field=models.ManyToManyField(blank=True, null=True, to='testapp.ExtraField', verbose_name='Extra fields'),
        ),
    ]
