# Generated by Django 4.0.1 on 2022-10-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_extrafield_remove_opdbillingtemp_bill_date_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrafield',
            options={'ordering': ['uhid']},
        ),
    ]
