# Generated by Django 4.0.1 on 2022-10-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_alter_extrafield_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdbillingtemp',
            name='extra_fields',
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='bill_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='bill_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='net_ammount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='outstanding_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='receive_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='service_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='uhid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemp',
            name='visit_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ExtraField',
        ),
    ]
