# Generated by Django 4.0.1 on 2022-10-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_extrafield_opdbillingtempsec'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdBillingTemper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('service_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('net_ammount', models.CharField(blank=True, max_length=50, null=True)),
                ('outstanding_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('receive_amount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
