# Generated by Django 4.0.1 on 2022-10-26 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opdpayment',
            old_name='cheque_card_dd_no',
            new_name='card_no',
        ),
        migrations.RenameField(
            model_name='opdpayment',
            old_name='GCR_No',
            new_name='utr_id',
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 26)),
        ),
        migrations.AlterField(
            model_name='opdpayment',
            name='mode_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('DEBIT/CREDIT CARD', 'DEBIT/CREDIT CARD'), ('WALLET', 'WALLET'), ('UPI', 'UPI')], default='CASH', max_length=30),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 26)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 26)),
        ),
    ]
