# Generated by Django 4.0.1 on 2022-10-28 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_rename_cheque_card_dd_no_opdpayment_card_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdbillingtemper',
            name='bill_date_time',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemper',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='opdbillingtemper',
            name='bill_no',
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 28)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 28)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 10, 28)),
        ),
    ]
