# Generated by Django 4.0.1 on 2022-11-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_bankmaster_opdpaymentmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdbillingmain',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
