# Generated by Django 4.0.1 on 2022-11-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0030_adv_visit_creation_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvPatientVisitMains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('visit_date_time', models.DateTimeField(auto_now_add=True)),
                ('visit_id', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('clinical_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.clinicalordepartment')),
                ('nurse_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.doctortable')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.visittyoemaster')),
            ],
        ),
    ]
