# Generated by Django 4.0.1 on 2022-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_alter_opdbillingsub_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillingsub',
            name='bill_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
