# Generated by Django 4.0.1 on 2022-11-18 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0039_opdbillingmain_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50)),
                ('bill_date_time', models.CharField(max_length=50)),
                ('uhid', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_no', models.CharField(max_length=50)),
                ('corporate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('net_amount', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('pay_amount', models.CharField(max_length=50)),
                ('paid_amount', models.CharField(max_length=50)),
                ('outstanding_amount', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
    ]
