# Generated by Django 4.0.1 on 2022-11-24 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0042_opdbillsettlement_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDBillSettlementTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('visit_id', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.CharField(max_length=50)),
                ('bill_amt', models.CharField(max_length=50)),
                ('payer', models.CharField(max_length=50)),
                ('tax', models.FloatField()),
                ('receivable_amt', models.FloatField()),
                ('received_amt', models.FloatField()),
                ('outstanding_amt', models.FloatField()),
                ('payment_amt', models.FloatField()),
                ('settle_date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active')),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 24)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 24)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 24)),
        ),
    ]
