# Generated by Django 4.0.1 on 2022-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0044_remove_opdbillsettlementtemp_payment_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='outstanding_amt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
