# Generated by Django 4.0.1 on 2022-11-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0045_alter_opdbillsettlementtemp_outstanding_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='receivable_amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='received_amt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
