# Generated by Django 4.0.1 on 2022-11-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0046_alter_opdbillsettlementtemp_receivable_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='outstanding_amt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='receivable_amt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='received_amt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='tax',
            field=models.CharField(max_length=50),
        ),
    ]
