# Generated by Django 4.0.1 on 2022-11-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0047_alter_opdbillsettlementtemp_outstanding_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='status',
            field=models.BooleanField(choices=[('active', 'active'), ('inactive', 'inactive')], default='True'),
        ),
    ]
