# Generated by Django 4.0.1 on 2022-11-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0048_alter_opdbillsettlementtemp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='bill_amt',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='bill_date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='bill_no',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='outstanding_amt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='payer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='receivable_amt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='received_amt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='tax',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='uhid',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='visit_id',
            field=models.CharField(max_length=500),
        ),
    ]
