# Generated by Django 4.0.1 on 2022-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0051_opdbillingmain_paid_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdbillsettlementtemp',
            name='status2',
            field=models.BooleanField(blank=True, choices=[('partialy', 'partialy'), ('fully', 'fully')], default='True', null=True),
        ),
    ]
