# Generated by Django 4.0.1 on 2022-11-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0052_opdbillsettlementtemp_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillsettlementtemp',
            name='status2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
