# Generated by Django 4.0.1 on 2022-11-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0054_opdbillingmain_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdPackageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=500)),
                ('package_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpdPackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('rate', models.FloatField()),
                ('net_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OpdPackageService_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=100)),
                ('total_services', models.CharField(max_length=100)),
                ('before_total_amt', models.CharField(max_length=100)),
                ('total_discount', models.CharField(max_length=100)),
                ('after_total_amt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpdPackageService_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('rate', models.FloatField()),
                ('net_amount', models.FloatField()),
            ],
        ),
    ]
