# Generated by Django 4.0.1 on 2022-11-30 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0055_opdpackagemaster_opdpackageservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('consultation_id', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_sub_category', models.CharField(max_length=100)),
                ('service_department', models.CharField(max_length=100)),
                ('service_sub_department', models.CharField(max_length=100)),
                ('service_charge', models.CharField(max_length=100)),
                ('cons_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_sub_category', models.CharField(max_length=100)),
                ('service_department', models.CharField(max_length=100)),
                ('service_sub_department', models.CharField(max_length=100)),
                ('service_charge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Investigation_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('investigation_id', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('Service_Type', models.CharField(max_length=100)),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('Service_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('medication_id', models.CharField(max_length=100)),
                ('mediaction_name', models.CharField(max_length=100)),
                ('shortcode', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('date_time', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='medicationTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaction_name', models.CharField(max_length=100)),
                ('shortcode', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('procedure_id', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_sub_category', models.CharField(max_length=100)),
                ('service_department', models.CharField(max_length=100)),
                ('service_sub_department', models.CharField(max_length=100)),
                ('service_charge', models.CharField(max_length=100)),
                ('pro_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_sub_category', models.CharField(max_length=100)),
                ('service_department', models.CharField(max_length=100)),
                ('service_sub_department', models.CharField(max_length=100)),
                ('service_charge', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 30)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 30)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 11, 30)),
        ),
    ]
