# Generated by Django 4.0.1 on 2022-12-01 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0057_createadmin_createuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifLinkOpdPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_id', models.CharField(max_length=100)),
                ('opd_package_id', models.CharField(max_length=100)),
                ('apply_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
    ]
