# Generated by Django 4.0.1 on 2022-12-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0059_doctoraccounting_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdBillingGetDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(max_length=50)),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('corporate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('service_id', models.CharField(max_length=50)),
                ('charges', models.FloatField()),
                ('unit', models.IntegerField()),
                ('pay_amount', models.FloatField(blank=True, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('outstanding_amount', models.FloatField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.FloatField()),
                ('discount', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
            ],
        ),
    ]
