# Generated by Django 4.0.1 on 2022-12-05 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0060_opdbillinggetdelete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoraccounting',
            name='bill_id',
        ),
        migrations.AddField(
            model_name='doctoraccounting',
            name='service_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctoraccounting',
            name='service_rate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 5)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 5)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 5)),
        ),
    ]
