# Generated by Django 4.0.1 on 2022-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0062_doctoraccounting_tariff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoraccounting',
            old_name='tariff_name',
            new_name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='doctoraccounting',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='doctoraccounting',
            name='tariff_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
