# Generated by Django 4.0.1 on 2022-12-12 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0064_opdbillingsub_doctor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAccountingTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('p_name', models.CharField(max_length=50)),
                ('p_age', models.CharField(max_length=50)),
                ('p_gender', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date_time', models.CharField(max_length=50)),
                ('service_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('dr_share', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
    ]
