# Generated by Django 4.0.1 on 2022-12-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0065_doctoraccountingtemp_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoraccountingtemp',
            name='dr_share1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctoraccountingtemp',
            name='dr_share2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctoraccountingtemp',
            name='dr_share3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
