# Generated by Django 4.0.1 on 2022-12-13 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0066_doctoraccountingtemp_dr_share1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=500)),
                ('profile_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('rate', models.FloatField()),
                ('net_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileService_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100)),
                ('total_services', models.CharField(max_length=100)),
                ('before_total_amt', models.CharField(max_length=100)),
                ('total_discount', models.CharField(max_length=100)),
                ('after_total_amt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileService_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('rate', models.FloatField()),
                ('net_amount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 13)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 13)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 13)),
        ),
    ]
