# Generated by Django 4.0.1 on 2022-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0068_servicetest_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetest',
            name='normal_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
