# Generated by Django 4.0.1 on 2022-12-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0069_alter_servicetest_normal_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileservice',
            name='discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileservice',
            name='net_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileservice',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileservice',
            name='rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileservice_temp',
            name='discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileservice_temp',
            name='net_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileservice_temp',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileservice_temp',
            name='rate',
            field=models.CharField(max_length=100),
        ),
    ]
