# Generated by Django 4.0.1 on 2022-12-16 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0073_remove_servicetest_normal_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileservice',
            old_name='discount',
            new_name='chield_range',
        ),
        migrations.RenameField(
            model_name='profileservice',
            old_name='net_amount',
            new_name='female_range',
        ),
        migrations.RenameField(
            model_name='profileservice',
            old_name='quantity',
            new_name='infant_range',
        ),
        migrations.RenameField(
            model_name='profileservice',
            old_name='rate',
            new_name='male_range',
        ),
        migrations.RenameField(
            model_name='profileservice_temp',
            old_name='discount',
            new_name='chield_range',
        ),
        migrations.RenameField(
            model_name='profileservice_temp',
            old_name='net_amount',
            new_name='female_range',
        ),
        migrations.RenameField(
            model_name='profileservice_temp',
            old_name='quantity',
            new_name='infant_range',
        ),
        migrations.RenameField(
            model_name='profileservice_temp',
            old_name='rate',
            new_name='male_range',
        ),
        migrations.AddField(
            model_name='profileservice',
            name='units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profileservice_temp',
            name='units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 16)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 16)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 16)),
        ),
    ]
