# Generated by Django 4.0.1 on 2022-12-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0074_rename_discount_profileservice_chield_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileServiceSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('infant_range', models.CharField(blank=True, max_length=100, null=True)),
                ('chield_range', models.CharField(blank=True, max_length=100, null=True)),
                ('male_range', models.CharField(blank=True, max_length=100, null=True)),
                ('female_range', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profileservice_main',
            name='after_total_amt',
        ),
        migrations.RemoveField(
            model_name='profileservice_main',
            name='before_total_amt',
        ),
        migrations.RemoveField(
            model_name='profileservice_main',
            name='total_discount',
        ),
    ]
