# Generated by Django 4.0.1 on 2022-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0075_profileservicesub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMasterlinkTarrif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_id', models.CharField(max_length=100)),
                ('profile_id', models.CharField(max_length=100)),
                ('apply_date', models.CharField(max_length=100)),
            ],
        ),
    ]
