# Generated by Django 4.0.1 on 2022-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0076_profilemasterlinktarrif'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInvestigation_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100)),
                ('uhid', models.CharField(max_length=100)),
                ('visit_no', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=100)),
                ('profile_id', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100)),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingInvestigation_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100)),
                ('profile_id', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
            ],
        ),
    ]
