# Generated by Django 4.0.1 on 2022-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0077_pendinginvestigation_main_pendinginvestigation_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100)),
                ('profile_id', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
            ],
        ),
    ]
