# Generated by Django 4.0.1 on 2022-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0078_labresultentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinginvestigation_main',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
