# Generated by Django 4.0.1 on 2022-12-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0080_saamplecollection_samplemaster_volumemaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saamplecollection',
            old_name='lab_service_id',
            new_name='test_id',
        ),
    ]
