# Generated by Django 4.0.1 on 2022-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0083_labresultentry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresultentry',
            name='status',
        ),
        migrations.AddField(
            model_name='samplecollected',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('completed', 'completed')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
