# Generated by Django 4.0.1 on 2022-12-19 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0084_remove_labresultentry_status_samplecollected_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTestlinkTarrif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_id', models.CharField(max_length=100)),
                ('service_test_id', models.CharField(max_length=100)),
                ('apply_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='servicetest',
            name='test_charges',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 19)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 19)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 19)),
        ),
    ]
