# Generated by Django 4.0.1 on 2022-12-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0085_servicetestlinktarrif_servicetest_test_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresultentry',
            name='PTID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinginvestigation_main',
            name='PTID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
