# Generated by Django 4.0.1 on 2022-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0086_labresultentry_ptid_pendinginvestigation_main_ptid'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecollected',
            name='PTID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='PTID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
