# Generated by Django 4.0.1 on 2022-12-20 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0087_samplecollected_ptid_samplecollection_ptid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresultentry',
            name='status',
            field=models.CharField(choices=[('in_range', 'in_range'), ('out_range', 'out_range')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 20)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 20)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 20)),
        ),
    ]
