# Generated by Django 4.0.1 on 2022-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0088_labresultentry_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultEntry_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTID', models.CharField(max_length=100)),
                ('test_id', models.CharField(max_length=100)),
                ('profile_id', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_range', 'in_range'), ('out_range', 'out_range')], max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('upadated_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Validation_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTID', models.CharField(max_length=100)),
                ('uhid', models.CharField(max_length=100)),
                ('validated_by', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
