# Generated by Django 4.0.1 on 2022-12-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0091_service_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Test',
        ),
    ]
