# Generated by Django 4.0.1 on 2022-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0092_delete_service_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('service_category', models.CharField(max_length=100)),
                ('service_sub_category', models.CharField(max_length=100)),
                ('service_department', models.CharField(max_length=100)),
                ('ServiceSubDepartment', models.CharField(max_length=100)),
                ('infant_range', models.CharField(blank=True, max_length=100, null=True)),
                ('chield_range', models.CharField(blank=True, max_length=100, null=True)),
                ('male_range', models.CharField(blank=True, max_length=100, null=True)),
                ('female_range', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(max_length=100)),
            ],
        ),
    ]
