# Generated by Django 4.0.1 on 2022-12-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0094_profileservice_service_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_test',
            name='methodology',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
