# Generated by Django 4.0.1 on 2022-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0096_servicetest_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinginvestigation_main',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinginvestigation_main',
            name='sub_department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplecollected',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplecollected',
            name='sub_department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
