# Generated by Django 4.0.1 on 2022-12-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0097_pendinginvestigation_main_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='doctor_sign_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
