# Generated by Django 4.0.1 on 2022-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0104_opdbillsettlement_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdbillingtemper',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemper',
            name='status',
            field=models.CharField(blank=True, default='Open', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingtemper',
            name='temp_bill_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
