# Generated by Django 4.0.1 on 2022-12-30 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0105_opdbillingtemper_created_at_opdbillingtemper_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 30)),
        ),
        migrations.AlterField(
            model_name='opdpackagemaster',
            name='package_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemaster',
            name='profile_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 30)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 30)),
        ),
    ]
