# Generated by Django 4.0.1 on 2022-12-31 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0106_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_type', models.CharField(max_length=100)),
                ('ward_cat', models.CharField(max_length=100)),
                ('bed_no', models.CharField(max_length=100)),
                ('bed_charge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BedChargeSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('admission_ID', models.CharField(max_length=100)),
                ('ward_type', models.CharField(max_length=100)),
                ('ward_cat', models.CharField(max_length=100)),
                ('bed_no', models.CharField(max_length=100)),
                ('bed_charge', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('admission_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('LAMA', 'LAMA'), ('DAMA', 'DAMA'), ('expired', 'Expired'), ('Normal', 'Normal')], max_length=100)),
                ('discharge_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
    ]
