# Generated by Django 4.0.1 on 2022-12-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0107_bedcharge_bedchargeslip_discharge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiRow',
        ),
        migrations.RemoveField(
            model_name='opdbillingtempsec',
            name='extra_fields',
        ),
        migrations.AddField(
            model_name='opdbillingmain',
            name='temp_bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingsub',
            name='temp_bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ExtraField',
        ),
        migrations.DeleteModel(
            name='OpdBillingTempsec',
        ),
    ]
