# Generated by Django 4.0.1 on 2022-12-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0108_delete_multirow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdbillingmain',
            name='package_profile_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
