# Generated by Django 4.0.1 on 2023-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0111_opdbillingpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdpayment',
            name='date_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
