# Generated by Django 4.0.1 on 2023-01-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0112_opdpayment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='bill_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfileChargeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=50)),
                ('profile_charge', models.CharField(max_length=50)),
                ('applicable_date', models.DateField()),
                ('inactive', models.BooleanField(blank=True, default=True, null=True)),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster')),
                ('ward_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardcategory')),
                ('ward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardtype')),
            ],
        ),
    ]
