# Generated by Django 4.0.1 on 2023-01-03 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0113_alter_credit_bill_date_time_profilechargemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsregistrationsallinone',
            name='patient_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images_patient'),
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 3)),
        ),
    ]
