# Generated by Django 4.0.1 on 2023-01-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0114_patientsregistrationsallinone_patient_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsregistrationsallinone',
            name='patient_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
