# Generated by Django 4.0.1 on 2023-01-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0115_alter_patientsregistrationsallinone_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdbillingsub',
            name='package_profile_amt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opdbillingsub',
            name='package_profile_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
