# Generated by Django 4.0.1 on 2023-01-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0118_opdpackageservice_service_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageChargeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=50)),
                ('package_charge', models.CharField(max_length=50)),
                ('applicable_date', models.DateField()),
                ('inactive', models.BooleanField(blank=True, default=True, null=True)),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.tariffmaster')),
                ('ward_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardcategory')),
                ('ward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.wardtype')),
            ],
        ),
    ]
