# Generated by Django 4.0.1 on 2023-01-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0119_packagechargemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdbillingtemper',
            name='Pr_Opd_sr_bill_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
