# Generated by Django 4.0.1 on 2023-01-09 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0120_opdbillingtemper_pr_opd_sr_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='generic',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='manufacturers',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='suppliers',
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 9)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 9)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 9)),
        ),
    ]
