# Generated by Django 4.0.1 on 2023-01-13 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPDapp', '0008_rename_roomdefination_room_defination_and_more'),
        ('testapp', '0122_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 13)),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPDapp.ipd_dept'),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 13)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 13)),
        ),
    ]
