# Generated by Django 4.0.1 on 2023-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0123_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedChargeSlip_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('admission_ID', models.CharField(max_length=100)),
                ('ward_type', models.CharField(max_length=100)),
                ('ward_cat', models.CharField(max_length=100)),
                ('bed_no', models.CharField(max_length=100)),
                ('bed_charge', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
