# Generated by Django 4.0.1 on 2023-01-30 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0126_admission_report_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Dialysis_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('closing_attendent', models.CharField(max_length=50)),
                ('completion_status', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('next_day_dialysis', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50)),
                ('bp_sitting_max', models.CharField(max_length=50)),
                ('bp_sitting_min', models.CharField(max_length=50)),
                ('bp_standing_max', models.CharField(max_length=50)),
                ('respiration', models.CharField(max_length=50)),
                ('pulse_sitting', models.CharField(max_length=50)),
                ('pulse_standing', models.CharField(max_length=50)),
                ('tempreture', models.CharField(max_length=50)),
                ('measured_wt', models.CharField(max_length=50)),
                ('wheelchair_wt', models.CharField(max_length=50)),
                ('prosthetic_wt', models.CharField(max_length=50)),
                ('condition_assessment', models.CharField(max_length=50)),
                ('prolonged_bleeding_at_punctured_sites', models.CharField(max_length=50)),
                ('weight_lost', models.CharField(max_length=50)),
                ('fluid_removed', models.CharField(max_length=50)),
                ('uf_rate', models.CharField(max_length=50)),
                ('heparin_Left', models.CharField(max_length=50)),
                ('total_heparin_infused', models.CharField(max_length=50)),
                ('dialyzer_rating', models.CharField(max_length=50)),
                ('bruit_thrill', models.CharField(max_length=50)),
                ('minimum_BP_max', models.CharField(max_length=50)),
                ('minimum_BP_min', models.CharField(max_length=50)),
                ('dialysis_odometer_end_eading', models.CharField(max_length=50)),
                ('completion_notes', models.TextField()),
                ('next_pre_dialysis_notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 30)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 30)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 30)),
        ),
    ]
