# Generated by Django 4.0.1 on 2023-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0127_post_dialysis_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_dialysis_details',
            name='bp_standing_min',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_dialysis_details',
            name='minimum_BP_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
