# Generated by Django 4.0.1 on 2023-01-31 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0129_pre_dialysis_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemotherapy_treatment_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('BSA', models.CharField(max_length=100)),
                ('histology', models.CharField(max_length=100)),
                ('drugs', models.CharField(max_length=100)),
                ('dose_m2', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('p_temp', models.CharField(max_length=100)),
                ('wht', models.CharField(max_length=100)),
                ('wbc', models.CharField(max_length=100)),
                ('hb', models.CharField(max_length=100)),
                ('plt', models.CharField(max_length=100)),
                ('uec', models.CharField(max_length=100)),
                ('remark1', models.CharField(max_length=100)),
                ('remark2', models.CharField(max_length=100)),
                ('remark3', models.CharField(max_length=100)),
                ('remark4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dialysis_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('dialysis_start', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('start_attendant', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('machine_status', models.CharField(max_length=100)),
                ('min_bp_time', models.CharField(max_length=100)),
                ('min_bp', models.CharField(max_length=100)),
                ('average_pulse', models.CharField(max_length=100)),
                ('average_vp', models.CharField(max_length=100)),
                ('avg_dial_pressure', models.CharField(max_length=100)),
                ('server_time', models.CharField(max_length=100)),
                ('post_equip_preparation', models.CharField(max_length=100)),
                ('completion_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 31)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 31)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 1, 31)),
        ),
    ]
