# Generated by Django 4.0.1 on 2023-02-01 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0131_chemotherapy_treatment_sheet_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nursing_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('hosp_no', models.CharField(max_length=100)),
                ('chemotherapy_protocol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nursing_Notes_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=30)),
                ('date_time', models.CharField(max_length=100)),
                ('nursing_notes', models.CharField(max_length=100)),
                ('name_sign', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 2, 1)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 2, 1)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 2, 1)),
        ),
    ]
