# Generated by Django 4.0.1 on 2023-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0134_estimate_bill_main_estimate_bill_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate_bill_main',
            name='uhid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estimate_bill_sub',
            name='uhid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
