# Generated by Django 4.0.1 on 2023-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0135_alter_estimate_bill_main_uhid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate_bill_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('services', models.CharField(max_length=300)),
                ('services_rate', models.CharField(max_length=300)),
            ],
        ),
    ]
