# Generated by Django 4.0.1 on 2023-02-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0137_estimate_bill_mains'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estimate_bill_main',
        ),
    ]
