# Generated by Django 4.0.1 on 2023-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0140_schedule_master_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintanence_Deatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100)),
                ('item_sub_id', models.CharField(max_length=100)),
                ('item_model_no', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
