# Generated by Django 4.0.1 on 2023-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0141_maintanence_deatils'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanence_deatils',
            name='due_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
