# Generated by Django 4.0.1 on 2023-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0144_preventory_maintanence_unplanned_maintanence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventory_maintanence',
            name='delay_days',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='unplanned_maintanence',
            name='resolve_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
