# Generated by Django 4.0.1 on 2023-02-09 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0145_preventory_maintanence_delay_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation_Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sub_id', models.CharField(max_length=100)),
                ('item_model_no', models.CharField(max_length=100)),
                ('done_by', models.CharField(max_length=100)),
                ('schedule_name', models.CharField(max_length=100)),
                ('dispensive', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=100)),
                ('validation_date', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 2, 9)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 2, 9)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 2, 9)),
        ),
    ]
