# Generated by Django 4.0.1 on 2023-03-06 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0147_maintanence_deatils_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbillinginfos',
            old_name='cardholder_name',
            new_name='nhif_ins_cor_id',
        ),
        migrations.RenameField(
            model_name='patientbillinginfos',
            old_name='corporate_name',
            new_name='nhif_ins_cor_name',
        ),
        migrations.RenameField(
            model_name='patientsregistrationsallinone',
            old_name='cardholder_name',
            new_name='ins_doc_upload',
        ),
        migrations.RenameField(
            model_name='patientsregistrationsallinone',
            old_name='corporate_name',
            new_name='next_of_kin',
        ),
        migrations.RenameField(
            model_name='patientsregistrationsallinone',
            old_name='emergency_contact_num',
            new_name='next_of_kin_mob_no',
        ),
        migrations.RenameField(
            model_name='patientsregistrationsallinone',
            old_name='emergency_contact_person',
            new_name='nhif_ins_cor_id',
        ),
        migrations.AddField(
            model_name='patientsregistrationsallinone',
            name='nhif_ins_cor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 6)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 6)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 6)),
        ),
    ]
