# Generated by Django 4.0.1 on 2023-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0148_rename_cardholder_name_patientbillinginfos_nhif_ins_cor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsregistrationsallinone',
            name='ins_doc_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
