# Generated by Django 4.0.1 on 2023-03-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0149_alter_patientsregistrationsallinone_ins_doc_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsregistrationsallinone',
            name='ins_doc_upload',
            field=models.ImageField(blank=True, null=True, upload_to='ins_document/'),
        ),
    ]
