# Generated by Django 4.0.1 on 2023-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0150_alter_patientsregistrationsallinone_ins_doc_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ins_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
