# Generated by Django 4.0.1 on 2023-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0153_patientinsdoctype_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsdoctype',
            name='billing_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinsdoctype',
            name='nhif_ins_corp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
