# Generated by Django 4.0.1 on 2023-03-08 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0154_patientinsdoctype_billing_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOpdBillingMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50)),
                ('bill_date_time', models.CharField(max_length=50)),
                ('uhid', models.CharField(max_length=50)),
                ('temp_bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_no', models.CharField(max_length=50)),
                ('corporate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('package_profile_id', models.CharField(blank=True, max_length=50, null=True)),
                ('net_amount', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('pay_amount', models.CharField(max_length=50)),
                ('paid_amount', models.CharField(max_length=50)),
                ('outstanding_amount', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_amt', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_amt_update_date', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
    ]
