# Generated by Django 4.0.1 on 2023-03-10 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0156_alter_opdbillingtemper_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentChemotherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_nhif_id', models.CharField(max_length=100)),
                ('patient_national_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('patient_email', models.CharField(max_length=100)),
                ('diagnosis', models.TextField(max_length=200)),
                ('chemotherapy_protocol', models.TextField(max_length=500)),
                ('inform_by_dr', models.CharField(max_length=100)),
                ('i_have', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('patient_sign', models.CharField(max_length=100)),
                ('patient_relative_sign', models.CharField(max_length=100)),
                ('witness', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refferal_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('dr', models.CharField(max_length=100)),
                ('re', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('diagnosis', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 10)),
        ),
    ]
