# Generated by Django 4.0.1 on 2023-03-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0157_consentchemotherapy_refferal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferal_notes',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
