# Generated by Django 4.0.1 on 2023-03-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0160_patientallergy_alter_centralisedadminview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('social_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=100, null=True)),
                ('tobacco', models.BooleanField(blank=True, default=False, null=True)),
                ('tobacco_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('alcohol', models.BooleanField(blank=True, default=False, null=True)),
                ('alcohol_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('OU', models.BooleanField(blank=True, default=False, null=True)),
                ('OU_corrected', models.BooleanField(blank=True, default=False, null=True)),
                ('OS', models.BooleanField(blank=True, default=False, null=True)),
                ('OS_corrected', models.BooleanField(blank=True, default=False, null=True)),
                ('OD', models.BooleanField(blank=True, default=False, null=True)),
                ('OD_corrected', models.BooleanField(blank=True, default=False, null=True)),
                ('heart_disease', models.BooleanField(blank=True, default=False, null=True)),
                ('diabetes', models.BooleanField(blank=True, default=False, null=True)),
                ('cancer', models.BooleanField(blank=True, default=False, null=True)),
                ('other_family_disease', models.CharField(blank=True, max_length=100, null=True)),
                ('alert', models.BooleanField(blank=True, default=False, null=True)),
                ('awake', models.BooleanField(blank=True, default=False, null=True)),
                ('oriented', models.BooleanField(blank=True, default=False, null=True)),
                ('unresponsive', models.BooleanField(blank=True, default=False, null=True)),
                ('response_to_pain', models.BooleanField(blank=True, default=False, null=True)),
                ('color_pink', models.BooleanField(blank=True, default=False, null=True)),
                ('color_palle', models.BooleanField(blank=True, default=False, null=True)),
                ('color_cyanosis', models.BooleanField(blank=True, default=False, null=True)),
                ('skin_warm', models.BooleanField(blank=True, default=False, null=True)),
                ('skin_cold', models.BooleanField(blank=True, default=False, null=True)),
                ('skin_hot', models.BooleanField(blank=True, default=False, null=True)),
                ('skin_dry', models.BooleanField(blank=True, default=False, null=True)),
                ('past_HTN', models.BooleanField(blank=True, default=False, null=True)),
                ('past_heart_disease', models.BooleanField(blank=True, default=False, null=True)),
                ('past_diabetes', models.BooleanField(blank=True, default=False, null=True)),
                ('past_cancer', models.BooleanField(blank=True, default=False, null=True)),
                ('past_HIV', models.BooleanField(blank=True, default=False, null=True)),
                ('past_TB', models.BooleanField(blank=True, default=False, null=True)),
                ('past_other_disease', models.CharField(blank=True, max_length=100, null=True)),
                ('past_surgery_gall_bladder', models.BooleanField(blank=True, default=False, null=True)),
                ('past_surgery_appendix', models.BooleanField(blank=True, default=False, null=True)),
                ('past_surgery_hernia', models.BooleanField(blank=True, default=False, null=True)),
                ('past_surgery_other', models.CharField(blank=True, max_length=100, null=True)),
                ('bleeding', models.BooleanField(blank=True, default=False, null=True)),
                ('skin_intact', models.BooleanField(blank=True, default=False, null=True)),
                ('skin_other', models.CharField(blank=True, max_length=100, null=True)),
                ('shortness_of_breath', models.BooleanField(blank=True, default=False, null=True)),
                ('Coughing', models.BooleanField(blank=True, default=False, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('vital_bp', models.CharField(blank=True, max_length=100, null=True)),
                ('vital_pulse', models.CharField(blank=True, max_length=100, null=True)),
                ('vital_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
