# Generated by Django 4.0.1 on 2023-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0164_advice_bill_id_advice_uhid_advice_visit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=100)),
                ('report', models.FileField(upload_to='lab_report/')),
            ],
        ),
    ]
