# Generated by Django 4.0.1 on 2023-03-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0166_opdbillingmain_checklist_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_Checklist_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_no', models.CharField(max_length=255)),
                ('checklist_date', models.DateField()),
                ('document_name', models.CharField(max_length=255)),
                ('prepare_status', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_CheckList_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, editable=False, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Checklist_Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_no', models.CharField(max_length=255)),
                ('checklist_date', models.DateField()),
                ('bill_no', models.CharField(max_length=255)),
                ('bill_datetime', models.DateTimeField()),
                ('uhid', models.CharField(max_length=50)),
                ('bill_amt', models.CharField(max_length=50)),
                ('net_amt', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Claim_Acknowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=255)),
                ('bill_datetime', models.DateTimeField()),
                ('uhid', models.CharField(max_length=50)),
                ('bill_amt', models.CharField(max_length=50)),
                ('net_amt', models.CharField(max_length=50)),
                ('claim_amt', models.CharField(max_length=50)),
                ('acknowledge', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Raising_Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=255)),
                ('bill_datetime', models.DateTimeField()),
                ('uhid', models.CharField(max_length=50)),
                ('bill_amt', models.CharField(max_length=50)),
                ('net_amt', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
