# Generated by Django 4.0.1 on 2023-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0167_insurance_checklist_child_insurance_checklist_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbillingmain',
            name='checklist_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillingmain',
            name='claim_amt',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbillingmain',
            name='claim_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
