# Generated by Django 4.0.1 on 2023-03-16 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0169_department_consumption_item_issue_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed_ItemStatus_Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('purchase_qty', models.CharField(max_length=50)),
                ('consume_qty', models.CharField(max_length=50)),
                ('in_hand_qty', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='department_consumption',
            name='grn_consume_hand_qty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department_consumption',
            name='opening_balance',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department_consumption',
            name='total_qty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ps_countersale_child',
            name='grn_consume_hand_qty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_batchwise',
            name='total_consume_qty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 16)),
        ),
    ]
