# Generated by Django 4.0.1 on 2023-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0170_detailed_itemstatus_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
