# Generated by Django 3.2.6 on 2023-03-17 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0171_alter_createuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralisedadminview',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder_child',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder_child',
            name='received_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tokencreationdone',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 17)),
        ),
    ]
