# Generated by Django 3.2.6 on 2023-03-18 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0172_auto_20230317_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Functions',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
        migrations.DeleteModel(
            name='UserProfileType',
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
    ]
