# Generated by Django 3.2.6 on 2023-03-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPDapp', '0008_rename_roomdefination_room_defination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0174_createuser_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='createuser',
            name='f_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Item Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createuser',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IPDapp.ipd_dept'),
            preserve_default=False,
        ),
    ]
