# Generated by Django 3.2.6 on 2023-03-27 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0175_auto_20230318_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 27)),
        ),
    ]
