# Generated by Django 4.0.1 on 2023-03-29 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0176_auto_20230327_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('D_GRG_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationProcedureTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('investigation_and_procedure', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('result_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ot_required', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentingComplaintTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateField(auto_now_add=True, null=True)),
                ('presenting_comp', models.CharField(max_length=50)),
                ('initial_comp', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 29)),
        ),
        migrations.CreateModel(
            name='PresentingComplaintSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateField(auto_now_add=True, null=True)),
                ('presenting_comp', models.CharField(max_length=50)),
                ('initial_comp', models.TextField()),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.presentingcomplaint')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationProcedureSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('investigation_and_procedure', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('result_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ot_required', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('D_GRG_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.diagnosis')),
            ],
        ),
    ]
