# Generated by Django 4.0.1 on 2023-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0177_diagnosistemp_investigationproceduretemp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premedicine',
            name='food_relations',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='premedicine',
            name='frequency',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='premedicine',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
