# Generated by Django 4.0.1 on 2023-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0178_alter_premedicine_food_relations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
