# Generated by Django 4.0.1 on 2023-03-30 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0179_alter_diagnosis_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsregistrationsallinone',
            name='ins_id_upload',
            field=models.ImageField(blank=True, null=True, upload_to='ins_id_document/'),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 3, 30)),
        ),
    ]
