# Generated by Django 4.0.1 on 2023-03-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0180_patientsregistrationsallinone_ins_id_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsregistrationsallinone',
            name='nhif_ins_cor_name',
            field=models.CharField(blank=True, default='Cash', max_length=100, null=True),
        ),
    ]
