# Generated by Django 4.0.1 on 2023-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0182_alter_patientsregistrationsallinone_sum_insured_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortable',
            name='doctor_appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
