# Generated by Django 4.0.1 on 2023-04-01 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0184_alter_doctortable_doctor_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 1)),
        ),
    ]
