# Generated by Django 3.2.6 on 2023-04-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0185_alter_tokencreations_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='storemaster',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='storemaster',
            name='main_store',
        ),
        migrations.AddField(
            model_name='createuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_store', to='testapp.storemaster'),
        ),
        migrations.AddField(
            model_name='storemaster',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AlterField(
            model_name='storemaster',
            name='store_type',
            field=models.CharField(choices=[('0', 'CPC'), ('1', 'MainStore'), ('2', 'SubStore')], max_length=100),
        ),
        migrations.AddField(
            model_name='createuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user_location', to='testapp.locationmaster'),
        ),
        migrations.AddField(
            model_name='storemaster',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
    ]
