# Generated by Django 3.2.6 on 2023-04-03 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0195_auto_20230402_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortable',
            name='doctor_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 3)),
        ),
    ]
