# Generated by Django 3.2.6 on 2023-04-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0201_auto_20230404_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdpayment',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='opdpayment',
            name='utr_id',
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='bank_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='mobile_nummber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='paid_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='pending_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='ref_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='status',
            field=models.CharField(default='fully completed', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opdpayment',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opdpayment',
            name='bill_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='opdpayment',
            name='card_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opdpayment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='opdpayment',
            name='mode_type',
            field=models.CharField(max_length=30),
        ),
    ]
