# Generated by Django 3.2.6 on 2023-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0202_auto_20230404_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opdpayment',
            old_name='amount',
            new_name='net_amount',
        ),
        migrations.AddField(
            model_name='opdpayment',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
