# Generated by Django 3.2.6 on 2023-04-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0204_auto_20230405_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateMaster',
            new_name='LabTemplateMaster',
        ),
        migrations.CreateModel(
            name='RadiologyTemplateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.profilemaster')),
            ],
        ),
    ]
