# Generated by Django 3.2.6 on 2023-04-06 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0205_auto_20230405_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtemplatemaster',
            name='service',
        ),
        migrations.RemoveField(
            model_name='radiologytemplatemaster',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='radiologytemplatemaster',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='labtemplatemaster',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.profilemaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtemplatemaster',
            name='profile_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologytemplatemaster',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicemaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 6)),
        ),
    ]
