# Generated by Django 3.2.6 on 2023-04-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0207_prescriptiondialysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescriptionDialysis',
        ),
    ]
