# Generated by Django 3.2.6 on 2023-04-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0208_delete_prescriptiondialysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDialysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('drid', models.CharField(blank=True, max_length=100, null=True)),
                ('prescription_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('s_date', models.CharField(max_length=100)),
                ('e_date', models.CharField(max_length=100)),
                ('dry_weight', models.CharField(max_length=100)),
                ('dry_weight_date', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('day1', models.CharField(max_length=100)),
                ('shift1', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('day2', models.CharField(max_length=100)),
                ('weekly', models.CharField(max_length=100)),
                ('shift2', models.CharField(blank=True, max_length=100, null=True)),
                ('day3', models.CharField(max_length=100)),
                ('shift3', models.CharField(max_length=100)),
                ('dialysis_membrane', models.CharField(blank=True, max_length=100, null=True)),
                ('day4', models.CharField(max_length=100)),
                ('shift4', models.CharField(max_length=100)),
                ('day5', models.CharField(max_length=100)),
                ('shift5', models.CharField(max_length=100)),
                ('dialysate_temp', models.CharField(max_length=100)),
                ('k_meql', models.CharField(max_length=100)),
                ('ca_meal', models.CharField(max_length=100)),
                ('mg_meal', models.CharField(max_length=100)),
                ('glucose', models.CharField(max_length=100)),
                ('target_bvp', models.CharField(max_length=100)),
                ('dialysate_flow', models.CharField(max_length=100)),
                ('profile1', models.CharField(max_length=100)),
                ('blood_flow', models.CharField(max_length=100)),
                ('profile2', models.CharField(max_length=100)),
                ('bicarb', models.CharField(max_length=100)),
                ('profile3', models.CharField(max_length=100)),
                ('na_meql', models.CharField(max_length=100)),
                ('profile4', models.CharField(max_length=100)),
                ('uf_rate', models.CharField(max_length=100)),
                ('ufr_profile', models.CharField(max_length=100)),
                ('initial_dose', models.CharField(max_length=100)),
                ('interim_dose', models.CharField(max_length=100)),
                ('total_heparin_bolus', models.CharField(max_length=100)),
                ('hourly', models.CharField(max_length=100)),
                ('cut_off_time', models.CharField(max_length=100)),
                ('heparin_profile', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
                ('dialysis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.dialysate_type')),
                ('dialyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.dialyzer')),
                ('heparin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.heparin_type')),
            ],
        ),
    ]
