# Generated by Django 4.1.2 on 2023-04-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0212_remove_inventory_itemmaster_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_itemmaster',
            name='Gst',
        ),
        migrations.AddField(
            model_name='inventory_itemmaster',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.servicedepartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory_itemmaster',
            name='tax',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
