# Generated by Django 4.1.2 on 2023-04-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0214_permanent_access_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbarcode',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
