# Generated by Django 4.0.1 on 2023-04-09 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0215_alter_patientbarcode_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortable',
            name='doctor_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 9)),
        ),
    ]
