# Generated by Django 4.1.2 on 2023-04-10 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0216_alter_doctortable_doctor_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencreations',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 4, 10)),
        ),
    ]
