# Generated by Django 4.0.1 on 2023-04-10 14:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0217_alter_tokencreations_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntraDialysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=30)),
                ('visit_id', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('completion_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IntraDialysisPerHourInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('visit_id', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('bp_mmhg1', models.CharField(max_length=50)),
                ('bp_mmhg2', models.CharField(max_length=50)),
                ('bp_time', models.CharField(max_length=50)),
                ('pulse', models.CharField(max_length=50)),
                ('total_uf_removal', models.CharField(max_length=50)),
                ('uf_rate', models.CharField(max_length=50)),
                ('blood_pump_flow_rate', models.CharField(max_length=50)),
                ('heparine_pump_infusion_rate', models.CharField(max_length=50)),
                ('dialysate_temp', models.CharField(max_length=50)),
                ('conductivity', models.CharField(max_length=50)),
                ('venus_pressure', models.CharField(max_length=50)),
                ('dialysate_pressure', models.CharField(max_length=50)),
                ('tmp', models.CharField(max_length=50)),
                ('dialysis_time', models.CharField(max_length=50)),
                ('dialysis_flow_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permanent_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('prim_aces', models.CharField(max_length=500)),
                ('date_initiation', models.CharField(max_length=500)),
                ('doctor_name', models.CharField(max_length=500)),
                ('access_site', models.CharField(max_length=500)),
                ('date_failure', models.CharField(max_length=500)),
                ('remark', models.CharField(max_length=500)),
                ('hospital_name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostEquip_preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('visit_id', models.CharField(max_length=50)),
                ('post_preparation', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Air Detector Armed'), ('2', 'Saline Clamped'), ('3', 'Pressure Limit Set'), ('4', 'Nurses Round'), ('5', 'Dialysate Counter Flow')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=50)),
                ('visit_id', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('plan', models.TextField()),
                ('intervention', models.TextField()),
                ('evalution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_aces', models.CharField(max_length=500)),
                ('date_initiation', models.CharField(max_length=500)),
                ('doctor_name', models.CharField(max_length=500)),
                ('access_site', models.CharField(max_length=500)),
                ('date_removal', models.CharField(max_length=500)),
                ('remark', models.CharField(max_length=500)),
                ('hospital_name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
