# Generated by Django 4.0.1 on 2023-04-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0218_intradialysis_intradialysisperhourinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_dialysis_details',
            name='visit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pre_dialysis_details',
            name='visit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
