# Generated by Django 4.1.7 on 2023-04-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0219_post_dialysis_details_visit_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postequip_preparation",
            name="post_preparation",
            field=models.CharField(
                choices=[
                    ("1", "Air Detector Armed"),
                    ("2", "Saline Clamped"),
                    ("3", "Pressure Limit Set"),
                    ("4", "Nurses Round"),
                    ("5", "Dialysate Counter Flow"),
                ],
                max_length=50,
            ),
        ),
    ]
