# Generated by Django 4.1.7 on 2023-04-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0220_alter_postequip_preparation_post_preparation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createuser",
            name="store",
        ),
        migrations.AddField(
            model_name="createuser",
            name="store",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="create_user_store",
                to="testapp.storemaster",
            ),
        ),
    ]
