# Generated by Django 4.1.7 on 2023-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0225_alter_tokencreations_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="opdbillingmain",
            name="claim_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opdbillingmain",
            name="lou_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
