# Generated by Django 4.1.7 on 2023-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0226_opdbillingmain_claim_no_opdbillingmain_lou_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurance_checklist_parent",
            name="batch_no",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurance_checklist_parent",
            name="claim_no",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurance_checklist_parent",
            name="lou_no",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
