# Generated by Django 4.1.7 on 2023-04-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0230_bookedappointments_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigationprocedure",
            name="bill_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="investigationprocedure",
            name="uhid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="investigationprocedure",
            name="visit_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientvisitmains",
            name="status",
            field=models.CharField(
                blank=True, default="open", max_length=500, null=True
            ),
        ),
    ]
