# Generated by Django 4.1.7 on 2023-04-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0234_alter_opdbillingmain_paid_claim_amt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opdbillingmain",
            name="paid_claim_amt",
        ),
    ]
