# Generated by Django 4.1.7 on 2023-04-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0236_opdbillingmain_paid_claim_amt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opdbillingmain",
            name="batch_no",
        ),
        migrations.RemoveField(
            model_name="opdbillingmain",
            name="paid_claim_amt",
        ),
        migrations.AddField(
            model_name="opdbillingmain",
            name="insurance_amt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
