# Generated by Django 4.1.7 on 2023-04-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0237_remove_opdbillingmain_batch_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opdbillingmain",
            name="batch_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opdbillingmain",
            name="paid_claim_amt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
