# Generated by Django 4.1.7 on 2023-04-17 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0238_opdbillingmain_batch_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientvisitmains",
            name="claim_no",
            field=models.CharField(
                blank=True, default="Not Initiated", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tokencreations",
            name="Date",
            field=models.DateField(default=datetime.date(2023, 4, 17)),
        ),
    ]
