# Generated by Django 4.1.7 on 2023-04-18 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usermanagementapp", "0007_alter_screenaccess_screen_access"),
        ("testapp", "0239_alter_patientvisitmains_claim_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createuser",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="create_user_location",
                to="testapp.locationmaster",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="createuser",
            name="store",
            field=models.ManyToManyField(
                blank=True, related_name="create_user_store", to="testapp.storemaster"
            ),
        ),
        migrations.AlterField(
            model_name="createuser",
            name="user_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="create_user_profile",
                to="usermanagementapp.screenaccess",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tokencreations",
            name="Date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
