# Generated by Django 4.1.7 on 2023-04-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0240_alter_createuser_location_alter_createuser_store_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PS_Sales_Payement_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("op_sale_no", models.CharField(blank=True, max_length=50, null=True)),
                ("sale_date", models.DateTimeField()),
                ("mode_type", models.CharField(max_length=30)),
                ("bill_amt", models.FloatField(blank=True, null=True)),
                ("paid_amount", models.FloatField(blank=True, null=True)),
                ("pending_amount", models.FloatField(blank=True, null=True)),
                ("bank_no", models.CharField(blank=True, max_length=100, null=True)),
                ("card_no", models.CharField(blank=True, max_length=100, null=True)),
                ("paid_by", models.CharField(blank=True, max_length=100, null=True)),
                ("ref_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mobile_nummber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "card_holder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Transfer_Request_Mainstore_Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_no", models.CharField(max_length=50)),
                ("request_date", models.DateField()),
                ("transfer_indent_no", models.CharField(max_length=50)),
                ("transfer_return_no", models.CharField(max_length=50)),
                ("intent_date", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("receive_status", models.CharField(max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.servicedepartment",
                    ),
                ),
                (
                    "indent_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.storemaster",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.locationmaster",
                    ),
                ),
                (
                    "request_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_request_store",
                        to="testapp.storemaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer_Request_Mainstore_Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_no", models.CharField(max_length=50)),
                ("request_date", models.DateField()),
                ("priority", models.CharField(max_length=50)),
                ("quantity", models.CharField(max_length=50)),
                ("rate", models.CharField(max_length=50)),
                ("issued_qty", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("receive_status", models.CharField(max_length=50)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.inventory_itemmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer_Intent_Temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trnasfer_indent_no", models.CharField(max_length=50)),
                ("intent_date", models.DateField()),
                ("priority", models.CharField(max_length=50)),
                ("quantity", models.CharField(max_length=50)),
                ("item_code", models.CharField(max_length=50)),
                ("item_belongs_to", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                ("rate", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=50)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cpc_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trnasfer_temp_store",
                        to="testapp.storemaster",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.servicedepartment",
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.inventory_itemmaster",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.locationmaster",
                    ),
                ),
                (
                    "main_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.storemaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer_Intent_Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trnasfer_indent_no", models.CharField(max_length=50)),
                ("intent_date", models.DateField()),
                ("total_amount", models.CharField(max_length=50)),
                ("p_status", models.CharField(max_length=50)),
                ("approval_status", models.CharField(max_length=50)),
                (
                    "cpc_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trnasfer_indent_store",
                        to="testapp.storemaster",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.servicedepartment",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.locationmaster",
                    ),
                ),
                (
                    "main_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.storemaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer_Intent_Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trnasfer_indent_no", models.CharField(max_length=50)),
                ("intent_date", models.DateField()),
                ("priority", models.CharField(max_length=50)),
                ("quantity", models.CharField(max_length=50)),
                ("rate", models.CharField(max_length=50)),
                ("item_code", models.CharField(max_length=50)),
                ("item_belongs_to", models.CharField(max_length=50)),
                ("received_qty", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("approval_status", models.CharField(max_length=50)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.inventory_itemmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manual_Stock_Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adjustment_id", models.CharField(max_length=50)),
                ("adjustment_date", models.DateTimeField()),
                ("batch_no", models.CharField(max_length=50)),
                ("expiry_date", models.CharField(max_length=50)),
                ("rate", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=50)),
                ("available_qty", models.CharField(max_length=50)),
                ("adjust_qty", models.CharField(max_length=50)),
                ("total_qty", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.inventory_itemmaster",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.locationmaster",
                    ),
                ),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.storemaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item_Transfer_Issue_Temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50)),
                ("batch_no", models.CharField(max_length=50)),
                ("expiry_date", models.CharField(max_length=50)),
                ("available_qty", models.CharField(max_length=50)),
                ("issued_qty", models.CharField(max_length=50)),
                ("rate", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                ("amount", models.CharField(max_length=50)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.inventory_itemmaster",
                    ),
                ),
            ],
        ),
    ]
