# Generated by Django 4.1.7 on 2023-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0241_ps_sales_payement_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item_issue_child",
            name="transfer_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item_issue_parent",
            name="transfer_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stock_batchwise_mainstore",
            name="transfer_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
