# Generated by Django 4.1.7 on 2023-04-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0243_item_return_tocpc_child_stock_transfer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item_return_tocpc_parent",
            name="indent_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indent_store",
                to="testapp.storemaster",
            ),
        ),
        migrations.AddField(
            model_name="item_return_tocpc_parent",
            name="request_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
