# Generated by Django 4.1.7 on 2023-04-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0244_item_return_tocpc_parent_indent_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_return_tocpc_parent",
            name="receiving_store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_return_receive_store",
                to="testapp.storemaster",
            ),
        ),
    ]
