# Generated by Django 4.1.7 on 2023-04-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0245_alter_item_return_tocpc_parent_receiving_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="patient_paid_amt",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
