# Generated by Django 4.1.7 on 2023-04-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0246_credit_patient_paid_amt"),
    ]

    operations = [
        migrations.AddField(
            model_name="opdbillingsub",
            name="order_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="opdbillingsub",
            name="service_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opdbillingsub",
            name="service_sub_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="opdbillingtemper",
            name="order_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="opdbillingtemper",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="testapp.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="opdbillingtemper",
            name="service_sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="testapp.servicesubcategory",
            ),
        ),
    ]
