# Generated by Django 4.1.7 on 2023-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0253_alter_opdbillingmain_paid_claim_amt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opdbillingmain",
            name="paid_claim_amt",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
