# Generated by Django 4.1.7 on 2023-04-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0255_insurance_payement_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department_consumption",
            name="consumption_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
