# Generated by Django 4.1.3 on 2023-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0257_alter_credit_patient_paid_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_batchwise_mainstore',
            name='expiry_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock_batchwise_mainstore',
            name='indent_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
