# Generated by Django 4.1.3 on 2023-04-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0258_alter_stock_batchwise_mainstore_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_batchwise_mainstore',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.vendormaster'),
        ),
    ]
