# Generated by Django 4.1.3 on 2023-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0259_alter_stock_batchwise_mainstore_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_return_supplier_child',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
