# Generated by Django 4.1.3 on 2023-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0260_item_return_supplier_child_movement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_return_supplier_child',
            name='return_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item_return_supplier_parent',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
