# Generated by Django 4.1.3 on 2023-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0262_item_return_supplier_child_opening_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeitem_return_temp',
            name='rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
