# Generated by Django 4.1.3 on 2023-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0263_makeitem_return_temp_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeitem_return_tocpc_temp',
            name='rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
