# Generated by Django 4.1.3 on 2023-04-27 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0265_insurance_payement_detail_location_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_payement_detail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='insurance_payement_detail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insurance_payement_detail',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.locationmaster'),
        ),
    ]
