# Generated by Django 4.0.1 on 2022-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0100_alter_centralisedadminview_date_and_more'),
        ('usermanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('service_department', models.ManyToManyField(to='testapp.ServiceDepartment')),
            ],
        ),
    ]
