# Generated by Django 4.0.1 on 2022-12-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagementapp', '0004_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labaccess',
            name='password',
        ),
    ]
