# Generated by Django 3.2.6 on 2023-03-18 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0173_auto_20230318_0939'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagementapp', '0005_remove_labaccess_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('screen_access', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMangement_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_access', models.CharField(max_length=1000)),
                ('ward_access', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to=settings.AUTH_USER_MODEL)),
                ('screen_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_access_name', to='usermanagementapp.screenaccess')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mng', to='testapp.createuser')),
            ],
        ),
    ]
