# Generated by Django 3.2.6 on 2023-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagementapp', '0006_screenaccess_usermangement_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenaccess',
            name='screen_access',
            field=models.TextField(),
        ),
    ]
